name: Analyze Python Files

on:
  push:
  pull_request:

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run analyze.py
        run: python analyze.py
